include:
  - local: '/.base-ci.yml'

#
# _/_/_/_/_/            _/
#    _/      _/  _/_/        _/_/_/    _/_/_/    _/_/    _/  _/_/
#   _/      _/_/      _/  _/    _/  _/    _/  _/_/_/_/  _/_/
#  _/      _/        _/  _/    _/  _/    _/  _/        _/
# _/      _/        _/    _/_/_/    _/_/_/    _/_/_/  _/
#                            _/        _/
#                       _/_/      _/_/
#

#
#     _/_/_/              _/  _/        _/
#    _/    _/  _/    _/      _/    _/_/_/
#   _/_/_/    _/    _/  _/  _/  _/    _/
#  _/    _/  _/    _/  _/  _/  _/    _/
# _/_/_/      _/_/_/  _/  _/    _/_/_/
#
.build-template:
  stage: build
  image: docker.maxiv.lu.se/centos7-build:latest
  script:
    - echo "This is a build stage for $RELEASE/$DIST/$ARCH"
    #- make clean
    - |
      echo "Make clean"
      rm -f ./*.*.rpm
      rm -rf build/

    #- make build DIST=$DIST ARCH=$ARCH
    - |
      export PROFILE=maxlab-${RELEASE}-${DIST}-${ARCH}

      echo "Make build for $PROFILE"
      maxpkg --dist=${DIST} sources --create-archive
      maxpkg --dist=${DIST} mockbuild --root=$PROFILE

      # Native RPM
      echo "Moving NATIVE RPMS files"
      SOURCE_DIR=results/$PROFILE
      SOURCE_FILES="*.*86*.rpm"
      TARGET_DIR=RPM/$RELEASE/$DIST/$ARCH
      safe_mv $SOURCE_DIR $SOURCE_FILES $TARGET_DIR

      # Architecture independant
      echo "Moving NOARCH RPMS files"
      SOURCE_FILES="*.noarch.rpm"
      TARGET_DIR=RPM/$RELEASE/$DIST/$ARCH
      safe_mv $SOURCE_DIR $SOURCE_FILES $TARGET_DIR

      # SOURCE RPM
      echo "Moving SRPMS files"
      SOURCE_DIR=results/$PROFILE
      SOURCE_FILES="*.src.rpm"
      TARGET_DIR=SRPMS/$RELEASE/$DIST/SRPMS
      safe_mv $SOURCE_DIR $SOURCE_FILES $TARGET_DIR

      # LOG FILES
      echo "Moving Logs files"
      SOURCE_DIR=results/$PROFILE
      SOURCE_FILES="*.log"
      TARGET_DIR=LOGS/$RELEASE/$DIST/$ARCH
      safe_mv $SOURCE_DIR $SOURCE_FILES $TARGET_DIR
  except:
    variables:
      - $UNSUPPORTED
  artifacts:
    paths:
      - RPM
      - SRPMS
      - LOGS
    expire_in: 1 week
