include:
  - local: '/.base-ci.yml'


#
# _/_/_/_/_/            _/
#    _/      _/  _/_/        _/_/_/    _/_/_/    _/_/    _/  _/_/
#   _/      _/_/      _/  _/    _/  _/    _/  _/_/_/_/  _/_/
#  _/      _/        _/  _/    _/  _/    _/  _/        _/
# _/      _/        _/    _/_/_/    _/_/_/    _/_/_/  _/
#                            _/        _/
#                       _/_/      _/_/
#

#
#     _/_/_/              _/  _/        _/
#    _/    _/  _/    _/      _/    _/_/_/
#   _/_/_/    _/    _/  _/  _/  _/    _/
#  _/    _/  _/    _/  _/  _/  _/    _/
# _/_/_/      _/_/_/  _/  _/    _/_/_/
#

.build-template:
  stage: build
  image: docker.maxiv.lu.se/centos7-build:latest
  script:
    - echo "This is a build stage for $RELEASE/$DIST/$ARCH"
    #- make clean
    - |
      echo "Make clean"
      rm -f ./*.*.rpm

    #- make build DIST=$DIST ARCH=$ARCH
    - |
      export PROFILE=maxlab-${RELEASE}-${DIST}-${ARCH}

      echo "Make build for $PROFILE"
      mkdir -p results/$PROFILE
      if [ -z "${PACKAGE_NAME}" ]
      then
        fpm -s python -t rpm --python-bin ${PYTHON_VERSION} --rpm-dist ${DIST} -p results/${PROFILE} ${FPM_FLAGS} --verbose .
      else
        fpm -s python -t rpm --python-bin ${PYTHON_VERSION} --rpm-dist ${DIST} -p results/${PROFILE} --name ${PACKAGE_NAME} ${FPM_FLAGS} --verbose .
      fi
      if [[ ${DEPLOY} = True ]]
      then
        # Architecture independant
        echo "Moving NOARCH RPMS files"
        SOURCE_DIR=results/$PROFILE
        SOURCE_FILES="*.noarch.rpm"
        TARGET_DIR=RPM/$RELEASE/$DIST/$ARCH
        safe_mv $SOURCE_DIR $SOURCE_FILES $TARGET_DIR
      else
        echo "Environment Variable DEPLOY is not defined for ${DIST} ${ARCH} ${PYTHON_VERSION}"
      fi
  except:
    variables:
      - $UNSUPPORTED
  artifacts:
    paths:
      - RPM
    expire_in: 1 week
